version: '3'

services:
  database:
    container_name: database
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - '4306:3306'
    volumes:
      - ./docker/database/data:/var/lib/mysql
  php-fpm:
    build:
      dockerfile: ./docker/php-fpm/Dockerfile
      context: .
    depends_on:
      - database
    command: bash -c "npm install &&
             composer install &&
             npm run dev &&
             php-fpm &&
             php artisan serve"
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}
    volumes:
      - .:/var/www
    ports:
    - '9001:9000'
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "8000:80"
      - "443:443"
